### ISSUE TITLE
Integrate window decorations with Controls 2/Fluid applications

### ISSUE THREAD

**Issue by iBelieve** [lirios/shell#23]
Pick up the primary dark color based on the application's primary color (used for the toolbar color).

**Comment by plfiorini** [comment]
Let's think about it in the context of server side decorations which eventually will land.
Client side decorations as QtWayland plugins are a PITA and limited although I like the idea more than server side decorations.
Though a Controls2/Fluid component like the Gtk+ HeaderBar would be cool and would allow us to do CSD with QML and have the primary color automatically.

**Comment by iBeliever** [comment]
On the topic of headerbars, there's a design for integrated toolbar/window decorations. See qmlos/fluid#29.

**Comment by iBeliever** [comment]
@plfiorini We now have properly colored client-side decorations thanks to https://github.com/lirios/shell/commit/31b9698b1816643749531d19f8971c69f3dec81a and https://github.com/lirios/fluid/commit/840abea79f791f6c1eac117d8e8e9f07f1467643. Do you want to close this issue or keep it open for server-side decorations?
