### ISSUE TITLE
PowerDialog list items text is white

### ISSUE THREAD

**Issue by plfiorini** [lirios/shell#38]
Text is white on white background, haven't checked yet but maybe Material.theme must be forced to Material.Light for the PowerDialog.

**Comment by iBeliever** [comment]
Hmm, this was working. And Material.theme is Material.Light. Not sure what's going on here.

**Comment by plfiorini** [comment]
Not sure either, I remember it was working. If it's of any help it seems a problem between Popup and ListItem.

**Comment by plfiorini** [comment]
Fixed, see https://github.com/lirios/fluid/issues/39
