### ISSUE TITLE
Show if an app is running in the launcher popup

### ISSUE THREAD

**Issue by iBelieve** [lirios/shell#44]
Clicking on a running app should focus it instead of launching it. We already have the Application class used by the LauncherModel, so we can come up with some method that shares application instances between the launcher panel and popup.

**Comment by plfiorini** [comment]
Weird it was working with previous versions, maybe we broke it.

**Comment by plfiorini** [comment]
Oh right you mean the launcher window not the panel?

**Comment by iBeliever** [comment]
Yes, the launcher window.
