### ISSUE TITLE
qmlos Archlinux packages

### ISSUE THREAD

**Issue by ceyhunnabiyev** [lirios/shell#62]
Could  you please provide   downloading and installing lirios packages from Archlinux repository  (AUR or other repository)??

**Comment by SunRain** [comment]
+1 for aur

**Comment by itcurious** [comment]
+1 for aur

**Comment by plfiorini** [comment]
Now that some basic structure is well defined this issue can be taken care.
I plan to start work on the packaging next week.

**Comment by plfiorini** [comment]
Issue moved to [lirios/lirios #14](https://github.com/lirios/lirios/issues/14) via [**ZenHub**](https://www.zenhub.com/)
