### ISSUE TITLE
io.liri.desktop.interface is not installed

### ISSUE THREAD

**Issue by Jack-Works** [lirios/shell#63]
Run liri-shell or liri-session, on Arch Linux
Um, which repo should I install?
Thanks.

**Comment by plfiorini** [comment]
@Jack-Works Run `sudo glib-compile-schemas /usr/share/glib-2.0/schemas/` to compile settings (of which io.liri.desktop.interface is a part of)

**Comment by Jack-Works** [comment]
It works! Thank you.
