### ISSUE TITLE
Fatal error at GreenIsland/greenisland_version.h: No such file or directory

### ISSUE THREAD

**Issue by steveunixson** [lirios/shell#67]
Make fails with: 
home/unixson/shell/compositor/main.cpp:34:45: fatal error: GreenIsland/greenisland_version.h: No such file or directory
 #include <GreenIsland/greenisland_version.h>
                                             ^
compilation terminated.
make[2]: *** [compositor/CMakeFiles/liri-shell.dir/build.make:198: compositor/CMakeFiles/liri-shell.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:260: compositor/CMakeFiles/liri-shell.dir/all] Error 2
make: *** [Makefile:161: all] Error 2

P.S I've installed all required dependencies and everything compiled smoothly till now

**Comment by plfiorini** [comment]
@steveunixson which branch is greenisland coming from, master or develop?

**Comment by steveunixson** [comment]
Develop. Should I build it from master?

**Comment by plfiorini** [comment]
This should be fixed now, besides greenisland was moved in Liri too as liri-wayland.
