### ISSUE TITLE
liri shell develop branch doesn't build with liri wayland/greenisland develop branch

### ISSUE THREAD

**Issue by n3rdopolis** [lirios/shell#68]
Hi

It seems that liri develop is compiling due to cmake issues due to missing 
`greenisland_add_cleint_protocol` in `helper/CMakeLists.txt` and `imports/shell/CMakeLists.txt`

also in liri greenisland/wayland I also had to run
```
sed -i '/GreenIslandCompositor/d' src/server/GreenIslandServerConfig.cmake.in
sed -i '/GreenIslandServerConfigExtras.cmake/d' src/server/GreenIslandServerConfig.cmake.in
```
as liri-shell was also trying to find these files being pulled by the CMake files

Remove those, and CMake runs, but the build fails as decorations/material/materialdecoration.cpp failes due to a parse error at line 319 at "IID"

Thanks

**Comment by plfiorini** [comment]
@n3rdopolis We are merging Hawaii and Papyros to make Liri OS. In preparation for Qt 5.8 I have copied greenisland here as liri-wayland and I'm in the middle of renaming everything.

liri-shell develop should build fine against greenisland develop

**Comment by n3rdopolis** [comment]
OK. I went for it, due to the fact that I now have QT 5.8...

**Comment by plfiorini** [comment]
Double cursor bug fixed.
