### ISSUE TITLE
Unable to close lock screen when password is empty

### ISSUE THREAD

**Issue by plfiorini** [lirios/shell#73]
1. Boot a live image
2. Enter the session by pressing ENTER at the login prompt
3. Press Meta+L or the lock button
4. Press ENTER to exit the lock screen

An error appears telling you that the password was not valid, but the liveuser has an empty password so typing ENTER should unlock the session.

**Comment by zigapk** [comment]
Additionally, if you lock screen and then press power button, the screen unlocks showing power dialog, which is simply bypassed by clicking anywhere.

**Comment by plfiorini** [comment]
@zigapk now pressing Power doesn't exit the lock screen

**Comment by plfiorini** [comment]
This is fixed now.
